/**
 * store-layout.ts — Single source of truth for all positioned objects in the 3D store.
 *
 * Categories:
 *   shelf    — gondola shelves and wall shelves
 *   counter  — checkout counter
 *   npc      — Vinny, Charlie, Kid, Tarantino, customers
 *   prop     — cooler, trophy shelf, bargain bin, detail items, etc.
 *   wall     — posters, signs, TV, bulletin board
 *   door     — entrance, employees only
 *   exterior — Pizza Palace, Laundromat, cars, lamps, etc.
 *
 * AUTO-GENERATED by /api/layout POST — do not edit manually.
 */

// ── Types ────────────────────────────────────────────────

export type ObjCategory = "shelf" | "counter" | "npc" | "prop" | "wall" | "door" | "exterior";

export interface LayoutObject {
  id: string;
  label: string;
  category: ObjCategory;
  x: number;
  y: number;
  z: number;
  rotY?: number;
  w?: number;
  d?: number;
  meta?: Record<string, unknown>;
}

export interface StoreLayout {
  version: number;
  objects: LayoutObject[];
}

// ── Layout Data ──────────────────────────────────────────

export const STORE_LAYOUT: StoreLayout = {
  version: 1,
  objects: [
    { id: "shelf-row1-horror", label: "HORROR / CULT", category: "shelf", x: -6.73, y: 0, z: -4.01, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"HORROR","color":"#00006e","backGenre":"CULT","backColor":"#00006e"} },
    { id: "shelf-row1-scifi", label: "SCI-FI / FOREIGN", category: "shelf", x: -3.06, y: 0, z: -4.77, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"SCI-FI","color":"#00006e","backGenre":"FOREIGN","backColor":"#00006e"} },
    { id: "shelf-row1-comedy", label: "COMEDY / INDIE", category: "shelf", x: 2.95, y: 0, z: -4.73, rotY: -0.262, w: 3.2, d: 0.6, meta: {"genre":"COMEDY","color":"#00006e","backGenre":"INDIE","backColor":"#00006e"} },
    { id: "shelf-row1-drama", label: "DRAMA / CLASSICS", category: "shelf", x: 6.54, y: 0, z: -3.79, rotY: -0.262, w: 3.2, d: 0.6, meta: {"genre":"DRAMA","color":"#00006e","backGenre":"CLASSICS","backColor":"#00006e"} },
    { id: "shelf-row2-action", label: "ACTION / THRILLER", category: "shelf", x: -6.35, y: 0, z: -1.41, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"ACTION","color":"#00006e","backGenre":"THRILLER","backColor":"#00006e"} },
    { id: "shelf-row2-western", label: "WESTERN / DOCS", category: "shelf", x: -2.42, y: 0, z: -2.43, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"WESTERN","color":"#00006e","backGenre":"DOCS","backColor":"#00006e"} },
    { id: "shelf-row2-romance", label: "ROMANCE / ANIMATED", category: "shelf", x: 2.65, y: 0, z: -2.5, rotY: -0.262, w: 3.2, d: 0.6, meta: {"genre":"ROMANCE","color":"#00006e","backGenre":"ANIMATED","backColor":"#00006e"} },
    { id: "shelf-row2-family", label: "FAMILY / CLASSICS", category: "shelf", x: 6.16, y: 0, z: -1.52, rotY: -0.262, w: 3.2, d: 0.6, meta: {"genre":"FAMILY","color":"#00006e","backGenre":"CLASSICS","backColor":"#00006e"} },
    { id: "shelf-row3-horror2", label: "HORROR / MYSTERY", category: "shelf", x: -5.82, y: 0, z: 1.05, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"HORROR","color":"#00006e","backGenre":"MYSTERY","backColor":"#00006e"} },
    { id: "shelf-row3-scifi2", label: "SCI-FI / FANTASY", category: "shelf", x: -2.12, y: 0, z: 0.07, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"SCI-FI","color":"#00006e","backGenre":"FANTASY","backColor":"#00006e"} },
    { id: "shelf-row3-comedy2", label: "COMEDY / KIDS", category: "shelf", x: 2.61, y: 0, z: -0.01, rotY: -0.262, w: 3.2, d: 0.6, meta: {"genre":"COMEDY","color":"#00006e","backGenre":"KIDS","backColor":"#00006e"} },
    { id: "shelf-row3-action2", label: "ACTION / ADVENTURE", category: "shelf", x: 6.01, y: 0, z: 0.9, rotY: -0.262, w: 3.2, d: 0.6, meta: {"genre":"ACTION","color":"#00006e","backGenre":"ADVENTURE","backColor":"#00006e"} },
    { id: "shelf-row4-musical", label: "MUSICAL / CONCERT", category: "shelf", x: -12.55, y: 0, z: -1.71, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"MUSICAL","color":"#00006e","backGenre":"CONCERT","backColor":"#00006e"} },
    { id: "shelf-row4-war", label: "WAR / HISTORY", category: "shelf", x: -2, y: 0, z: 2.71, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"WAR","color":"#00006e","backGenre":"HISTORY","backColor":"#00006e"} },
    { id: "shelf-row4-anime", label: "ANIME / MARTIAL ARTS", category: "shelf", x: -5.75, y: 0, z: 3.66, rotY: 0.262, w: 3.2, d: 0.6, meta: {"genre":"ANIME","color":"#00006e","backGenre":"MARTIAL ARTS","backColor":"#00006e"} },
    { id: "shelf-row4-sports", label: "SPORTS / NATURE", category: "shelf", x: 3.7, y: 0, z: 2.26, rotY: -0.262, w: 3.2, d: 0.6, meta: {"genre":"SPORTS","color":"#00006e","backGenre":"NATURE","backColor":"#00006e"} },
    { id: "wallshelf-back-drama", label: "Wall: NEW RELEASES", category: "shelf", x: 0, y: 0, z: -6.85, w: 18, d: 0.3, meta: {"genre":"NEW","color":"#ec4899","rotation":[0,0,0],"width":18} },
    { id: "new-releases-wall", label: "NEW RELEASES (wall)", category: "shelf", x: 0, y: 0, z: -6.85, w: 19, d: 0.3, meta: {"type":"new-releases-display"} },
    { id: "staff-picks", label: "Staff Picks", category: "prop", x: 9.75, y: 1.2, z: -2.65, w: 0.4, d: 1.2, meta: {"rotation":[0,-1.5707963267948966,0]} },
    { id: "counter", label: "COUNTER", category: "counter", x: 7, y: 0, z: 5, w: 6, d: 1.2 },
    { id: "vinny", label: "Vinny", category: "npc", x: 7, y: 0, z: 5.8, w: 0.6, d: 0.6, meta: {"role":"clerk"} },
    { id: "charlie", label: "Charlie", category: "npc", x: -7.42, y: -0.05, z: 0.67, w: 0.6, d: 0.6, meta: {"role":"regular"} },
    { id: "kid", label: "Kid", category: "npc", x: 8.28, y: -0.05, z: 0.98, w: 0.4, d: 0.4, meta: {"role":"kid"} },
    { id: "trophy-shelf", label: "Trophy Shelf", category: "prop", x: 9.71, y: 0, z: -4.88, w: 0.6, d: 2.5, meta: {"rotation":[0,-1.5707963267948966,0]} },
    { id: "plant", label: "Plant", category: "prop", x: 9.5, y: 0, z: -6.5, w: 0.4, d: 0.4 },
    { id: "trash-can", label: "Trash Can", category: "prop", x: -13, y: 0, z: 4.94, w: 0.35, d: 0.35 },
    { id: "return-bin", label: "Return Bin", category: "prop", x: 3.5, y: 0, z: 5.2, w: 0.8, d: 0.6 },
    { id: "bargain-crate", label: "2-for-$1 Crate", category: "prop", x: -12.74, y: 0, z: 2.98, w: 0.9, d: 0.7 },
    { id: "poster-jaws", label: "JAWS", category: "wall", x: -7, y: 1.8, z: -6.95, w: 0.8, d: 0.2 },
    { id: "poster-alien", label: "ALIEN", category: "wall", x: -9, y: 1.8, z: -6.95, w: 0.8, d: 0.2 },
    { id: "poster-blade", label: "BLADE RUNNER", category: "wall", x: 7, y: 1.8, z: -6.95, w: 0.8, d: 0.2 },
    { id: "poster-raiders", label: "RAIDERS", category: "wall", x: 9, y: 1.8, z: -6.95, w: 0.8, d: 0.2 },
    { id: "poster-shining", label: "THE SHINING", category: "wall", x: -9.9, y: 2, z: -2.78, rotY: 1.5707963267948966, w: 0.2, d: 0.8 },
    { id: "poster-starwars", label: "STAR WARS", category: "wall", x: -9.96, y: 2, z: 1.32, rotY: 1.5707963267948966, w: 0.2, d: 0.8 },
    { id: "poster-bttf", label: "BACK TO FUTURE", category: "wall", x: 9.84, y: 2, z: 1.5, rotY: -1.5707963267948966, w: 0.2, d: 0.8 },
    { id: "poster-et", label: "E.T.", category: "wall", x: 9.98, y: 2, z: -1.14, rotY: -1.5707963267948966, w: 0.2, d: 0.8 },
    { id: "neon-sign", label: "FRIDAY NIGHT VIDEO", category: "wall", x: 0, y: 3.1, z: -6.85, w: 5.8, d: 0.15 },
    { id: "be-kind-sign", label: "BE KIND REWIND", category: "wall", x: -9.88, y: 2, z: 2.5, rotY: 1.5707963267948966, w: 0.2, d: 1.5 },
    { id: "late-fees-sign", label: "LATE FEES", category: "wall", x: 9.9, y: 1.5, z: 5.2, rotY: -1.5707963267948966, w: 0.2, d: 1 },
    { id: "rewards-sign", label: "REWARDS MEMBER?", category: "wall", x: 7, y: 2.8, z: 5, rotY: 3.141592653589793, w: 2.5, d: 0.15 },
    { id: "open-sign", label: "OPEN", category: "wall", x: -4, y: 2.3, z: 7, w: 1, d: 0.15 },
    { id: "store-hours", label: "STORE HOURS", category: "wall", x: 4, y: 1.8, z: 7.05, w: 1.3, d: 0.9 },
    { id: "promo-board", label: "STORE SPECIALS", category: "wall", x: 9.84, y: 1.72, z: 3.05, rotY: -1.5707963267948966, w: 0.2, d: 1 },
    { id: "challenge-board", label: "CHALLENGE BOARD", category: "wall", x: -6.95, y: 1.62, z: 6.23, w: 0.2, d: 0.72 },
    { id: "tv-left", label: "CRT TV (left)", category: "wall", x: -9.05, y: 2.2, z: 0, w: 0.3, d: 1.2, meta: {"yaw":1.3907963267948966,"tilt":0.12,"scale":0.84} },
    { id: "tv-right", label: "CRT TV (right)", category: "wall", x: 9.28, y: 2.26, z: 0, w: 0.3, d: 1, meta: {"yaw":-1.3907963267948966,"tilt":0.12,"scale":0.7} },
    { id: "bulletin-board", label: "Bulletin Board", category: "wall", x: -9.92, y: 1.6, z: 4.8, rotY: 1.5707963267948966, w: 0.2, d: 1.2 },
    { id: "clock-counter", label: "Wall Clock", category: "wall", x: 9.9, y: 2.8, z: 6.2, rotY: -1.5707963267948966, w: 0.5, d: 0.5 },
    { id: "wall-phone", label: "Wall Phone", category: "wall", x: 9.8, y: 2.2, z: 5.3, rotY: -1.5707963267948966, w: 0.15, d: 0.25 },
    { id: "employees-door", label: "EMPLOYEES ONLY", category: "door", x: -9.93, y: 0, z: -5.19, rotY: 1.5707963267948966, w: 0.2, d: 0.9 },
    { id: "pizza-building", label: "PIZZA PALACE", category: "exterior", x: -13, y: 0, z: 7, w: 6, d: 0.3 },
    { id: "pizza-door", label: "Pizza Door", category: "exterior", x: -12.5, y: 0, z: 7.16, w: 1, d: 0.2 },
    { id: "pizza-window", label: "Pizza Window", category: "exterior", x: -13.8, y: 0, z: 7.17, w: 2, d: 0.2 },
    { id: "laundro-building", label: "LAUNDROMAT", category: "exterior", x: 13, y: 0, z: 7, w: 6, d: 0.3 },
    { id: "laundro-door", label: "Laundro Door", category: "exterior", x: 13.5, y: 0, z: 7.16, w: 1, d: 0.2 },
    { id: "laundro-window", label: "Laundro Window", category: "exterior", x: 12, y: 0, z: 7.17, w: 2.2, d: 0.2 },
    { id: "laundro-open", label: "Laundro OPEN", category: "exterior", x: 11.2, y: 0, z: 7.25, w: 0.7, d: 0.35 },
    { id: "sidewalk", label: "Sidewalk", category: "exterior", x: 0, y: 0, z: 7.8, w: 22, d: 1.5 },
    { id: "car-sedan", label: "Sedan", category: "exterior", x: 5, y: 0, z: 11, w: 2, d: 1 },
    { id: "car-van", label: "Van", category: "exterior", x: -3.68, y: 0, z: 11.81, rotY: 3.141592653589793, w: 2, d: 1 },
    { id: "car-suv", label: "SUV", category: "exterior", x: 1, y: 0, z: 12.5, w: 2, d: 1 },
    { id: "car-hatchback", label: "Hatchback", category: "exterior", x: -7, y: 0, z: 12.5, rotY: 3.141592653589793, w: 2, d: 1 },
    { id: "car-taxi", label: "Taxi", category: "exterior", x: 8, y: 0, z: 12.5, w: 2, d: 1 },
    { id: "car-sedan2", label: "Sedan 2", category: "exterior", x: -10.07, y: 0, z: 13.06, rotY: 3.141592653589793, w: 2, d: 1 },
    { id: "car-police", label: "Police Car", category: "exterior", x: 12.86, y: 0, z: 10.53, w: 2, d: 1 },
    { id: "car-delivery", label: "Delivery Van", category: "exterior", x: -2.38, y: 0, z: 13.68, rotY: 1.571, w: 2, d: 1 },
    { id: "lamp-1", label: "Lamp Post", category: "exterior", x: -5.94, y: 0, z: 14.75, w: 0.3, d: 0.3 },
    { id: "lamp-2", label: "Lamp Post", category: "exterior", x: 0, y: 0, z: 14, w: 0.3, d: 0.3 },
    { id: "lamp-3", label: "Lamp Post", category: "exterior", x: 6.12, y: 0, z: 14.63, w: 0.3, d: 0.3 },
  ],
};

// ── Helpers ──────────────────────────────────────────────

const _objectMap = new Map<string, LayoutObject>();
for (const obj of STORE_LAYOUT.objects) {
  _objectMap.set(obj.id, obj);
}

export function getObjectById(id: string): LayoutObject | undefined {
  return _objectMap.get(id);
}

export function getObjectsByCategory(category: ObjCategory): LayoutObject[] {
  return STORE_LAYOUT.objects.filter(o => o.category === category);
}

/**
 * Returns shelf rows in the same format Store.tsx SHELF_ROWS used to use.
 * Only includes gondola shelves (not wall shelves).
 */
export function getShelfRows(): { x: number; z: number; genre: string; color: string; backGenre: string; backColor: string; rotY: number }[] {
  return STORE_LAYOUT.objects
    .filter(o => o.id.startsWith("shelf-row"))
    .map(o => ({
      x: o.x,
      z: o.z,
      genre: (o.meta?.genre as string) || "",
      color: (o.meta?.color as string) || "#8B5E3C",
      backGenre: (o.meta?.backGenre as string) || "",
      backColor: (o.meta?.backColor as string) || "#444",
      rotY: o.rotY || 0,
    }));
}
