/**
 * store-layout.ts — Single source of truth for all positioned objects in the 3D store.
 *
 * Categories:
 *   shelf    — gondola shelves and wall shelves
 *   counter  — checkout counter
 *   npc      — Vinny, Charlie, Kid, Tarantino, customers
 *   prop     — cooler, trophy shelf, bargain bin, detail items, etc.
 *   wall     — posters, signs, TV, bulletin board
 *   door     — entrance, employees only
 *   exterior — Pizza Palace, Laundromat, cars, lamps, etc.
 *
 * AUTO-GENERATED by /api/layout POST — do not edit manually.
 */

import { resolvePrefabDefinition } from "./store-prefabs";

// ── Types ────────────────────────────────────────────────

export type ObjCategory = "shelf" | "counter" | "npc" | "prop" | "wall" | "door" | "exterior";

export interface LayoutInteraction {
  type: string;
  label: string;
  data?: string;
}

export interface LayoutCollider {
  type: "box";
  enabled?: boolean;
  width?: number;
  depth?: number;
  offsetX?: number;
  offsetZ?: number;
}

export interface LayoutObject {
  id: string;
  label: string;
  category: ObjCategory;
  x: number;
  y: number;
  z: number;
  prefab?: string;
  rotY?: number;
  w?: number;
  d?: number;
  hidden?: boolean;
  locked?: boolean;
  layer?: string;
  interaction?: LayoutInteraction;
  collider?: LayoutCollider;
  meta?: Record<string, unknown>;
}

export interface StoreLayout {
  version: number;
  objects: LayoutObject[];
}

export interface ResolvedLayoutObject extends LayoutObject {
  prefabId?: string;
  hidden: boolean;
  locked: boolean;
  layer: string;
  interaction?: LayoutInteraction;
  collider?: LayoutCollider;
}

export interface WorldCollider {
  id: string;
  x: number;
  z: number;
  hw: number;
  hd: number;
}

// ── Layout Data ──────────────────────────────────────────

export const STORE_LAYOUT: StoreLayout = {
  version: 1,
  objects: [
    { id: "shelf-row1-action", label: "CLASSICS", category: "shelf", x: -6.5, y: 0, z: -4.5, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"CLASSICS","color":"#00006e","backGenre":"DRAMA","backColor":"#00006e"} },
    { id: "shelf-row1-action2", label: "CLASSICS", category: "shelf", x: -3.06, y: 0, z: -4.8, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"CLASSICS","color":"#00006e","backGenre":"DRAMA","backColor":"#00006e"} },
    { id: "shelf-row1-comedy", label: "WESTERN", category: "shelf", x: 2.95, y: 0, z: -4.73, prefab: "shelf/gondola", rotY: -0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"WESTERN","color":"#00006e","backGenre":"HORROR","backColor":"#00006e"} },
    { id: "shelf-row1-comedy2", label: "MUSICALS", category: "shelf", x: 6.4, y: 0, z: -4.42, prefab: "shelf/gondola", rotY: -0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"MUSICAL","color":"#00006e","backGenre":"HORROR","backColor":"#00006e"} },
    { id: "shelf-row2-horror", label: "ACTION", category: "shelf", x: -6.19, y: 0, z: -1.97, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"ACTION","color":"#00006e","backGenre":"THRILLER","backColor":"#00006e"} },
    { id: "shelf-row2-horror2", label: "ADVENTURE", category: "shelf", x: -2.78, y: 0, z: -2.27, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"ADVENTURE","color":"#00006e","backGenre":"THRILLER","backColor":"#00006e"} },
    { id: "shelf-row2-drama", label: "SCI-FI", category: "shelf", x: 2.65, y: 0, z: -2.5, prefab: "shelf/gondola", rotY: -0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"SCI-FI","color":"#00006e","backGenre":"ACTION","backColor":"#00006e"} },
    { id: "shelf-row2-drama2", label: "FANTASY", category: "shelf", x: 6.17, y: 0, z: -2.13, prefab: "shelf/gondola", rotY: -0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"FANTASY","color":"#00006e","backGenre":"ADVENTURE","backColor":"#00006e"} },
    { id: "shelf-row3-scifi", label: "HORROR", category: "shelf", x: -5.86, y: 0, z: 0.41, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"HORROR","color":"#00006e","backGenre":"ACTION","backColor":"#00006e"} },
    { id: "shelf-row3-scifi2", label: "HORROR", category: "shelf", x: -2.6, y: 0, z: 0.12, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"HORROR","color":"#00006e","backGenre":"ADVENTURE","backColor":"#00006e"} },
    { id: "shelf-row3-family", label: "DRAMA", category: "shelf", x: 2.6, y: 0, z: -0.13, prefab: "shelf/gondola", rotY: -0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"DRAMA","color":"#00006e","backGenre":"ROMANCE","backColor":"#00006e"} },
    { id: "shelf-row3-family2", label: "DRAMA", category: "shelf", x: 6.01, y: 0, z: 0.18, prefab: "shelf/gondola", rotY: -0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"DRAMA","color":"#00006e","backGenre":"FAMILY","backColor":"#00006e"} },
    { id: "shelf-row4-musical2", label: "COMEDY", category: "shelf", x: -5.83, y: 0, z: 2.86, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"COMEDY","color":"#00006e","backGenre":"ROMANCE","backColor":"#00006e"} },
    { id: "shelf-row4-western", label: "COMEDY", category: "shelf", x: -2.38, y: 0, z: 2.59, prefab: "shelf/gondola", rotY: 0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"COMEDY","color":"#00006e","backGenre":"FAMILY","backColor":"#00006e"} },
    { id: "shelf-row4-western2", label: "KIDS", category: "shelf", x: 3.77, y: 0, z: 2.25, prefab: "shelf/gondola", rotY: -0.087, w: 3.2, d: 0.6, layer: "fixtures", interaction: {"type":"shelf","label":"Browse Shelf"}, collider: {"type":"box","enabled":true,"width":2.6,"depth":0.4}, meta: {"genre":"KIDS","color":"#00006e","backGenre":"FAMILY","backColor":"#00006e"} },
    { id: "new-releases-wall", label: "NEW RELEASES (wall)", category: "shelf", x: 0, y: 0, z: -6.97, prefab: "shelf/new-releases-wall", w: 19, d: 0.3, layer: "fixtures", collider: {"type":"box","enabled":true,"width":19,"depth":0.4}, meta: {"type":"new-releases-display"} },
    { id: "staff-picks", label: "Staff Picks", category: "prop", x: 9.75, y: 1.2, z: -2.65, w: 0.4, d: 1.2, layer: "prop", meta: {"rotation":[0,-1.5707963267948966,0]} },
    { id: "counter", label: "COUNTER", category: "counter", x: 7, y: 0, z: 5, prefab: "fixture/counter", w: 6, d: 1.2, layer: "fixtures", collider: {"type":"box","enabled":true,"width":6.4,"depth":1.6} },
    { id: "vinny", label: "Vinny", category: "npc", x: 7, y: 0, z: 5.8, w: 0.6, d: 0.6, layer: "npc", meta: {"role":"clerk"} },
    { id: "charlie", label: "Charlie", category: "npc", x: -7.81, y: -0.05, z: 2.52, w: 0.6, d: 0.6, layer: "npc", meta: {"role":"regular"} },
    { id: "kid", label: "Kid", category: "npc", x: 8.28, y: -0.05, z: 0.98, w: 0.4, d: 0.4, layer: "npc", meta: {"role":"kid"} },
    { id: "trophy-shelf", label: "Trophy Shelf", category: "prop", x: 9.71, y: 0, z: -4.88, prefab: "prop/trophy-shelf", w: 0.6, d: 2.5, layer: "props", interaction: {"type":"trophy","label":"View Collection"}, collider: {"type":"box","enabled":true,"width":0.8,"depth":2.8}, meta: {"rotation":[0,-1.5707963267948966,0]} },
    { id: "plant", label: "Plant", category: "prop", x: 9.5, y: 0, z: -6.5, w: 0.4, d: 0.4, layer: "prop" },
    { id: "return-bin", label: "Return Bin", category: "prop", x: 3.5, y: 0, z: 5.2, prefab: "prop/return-bin", w: 0.8, d: 0.6, layer: "props", interaction: {"type":"return_slot","label":"Drop Returns Here"}, collider: {"type":"box","enabled":true,"width":1,"depth":0.8} },
    { id: "poster-jaws", label: "JAWS", category: "wall", x: -7, y: 1.8, z: -6.95, prefab: "wall/poster", w: 0.8, d: 0.2, layer: "wall-decor" },
    { id: "poster-alien", label: "ALIEN", category: "wall", x: -9, y: 1.8, z: -6.95, prefab: "wall/poster", w: 0.8, d: 0.2, layer: "wall-decor" },
    { id: "poster-blade", label: "BLADE RUNNER", category: "wall", x: 7, y: 1.8, z: -6.95, prefab: "wall/poster", w: 0.8, d: 0.2, layer: "wall-decor" },
    { id: "poster-raiders", label: "RAIDERS", category: "wall", x: 9, y: 1.8, z: -6.95, prefab: "wall/poster", w: 0.8, d: 0.2, layer: "wall-decor" },
    { id: "poster-shining", label: "THE SHINING", category: "wall", x: -9.9, y: 2, z: -2.78, prefab: "wall/poster", rotY: 1.571, w: 0.2, d: 0.8, layer: "wall-decor" },
    { id: "poster-starwars", label: "STAR WARS", category: "wall", x: -9.96, y: 2, z: 1.32, prefab: "wall/poster", rotY: 1.571, w: 0.2, d: 0.8, layer: "wall-decor" },
    { id: "poster-bttf", label: "BACK TO FUTURE", category: "wall", x: 9.84, y: 2, z: 1.5, prefab: "wall/poster", rotY: -1.571, w: 0.2, d: 0.8, layer: "wall-decor" },
    { id: "poster-et", label: "E.T.", category: "wall", x: 9.98, y: 2, z: -1.14, prefab: "wall/poster", rotY: -1.571, w: 0.2, d: 0.8, layer: "wall-decor" },
    { id: "neon-sign", label: "FRIDAY NIGHT VIDEO", category: "wall", x: 0, y: 3.1, z: -6.85, prefab: "sign/neon", w: 5.8, d: 0.15, layer: "wall-decor" },
    { id: "be-kind-sign", label: "BE KIND REWIND", category: "wall", x: -9.88, y: 2, z: 2.5, prefab: "sign/plastic-store", rotY: 1.571, w: 0.2, d: 1.5, layer: "wall-decor" },
    { id: "late-fees-sign", label: "LATE FEES", category: "wall", x: 9.9, y: 1.5, z: 5.2, prefab: "sign/plastic-store", rotY: -1.571, w: 0.2, d: 1, layer: "wall-decor" },
    { id: "rewards-sign", label: "REWARDS MEMBER?", category: "wall", x: 7, y: 2.8, z: 5, prefab: "sign/plastic-store", rotY: 3.142, w: 2.5, d: 0.15, layer: "wall-decor" },
    { id: "open-sign", label: "OPEN", category: "wall", x: -4, y: 2.3, z: 7, prefab: "sign/open", w: 1, d: 0.15, layer: "wall-decor" },
    { id: "store-hours", label: "STORE HOURS", category: "wall", x: 4, y: 1.8, z: 7.05, prefab: "sign/store-hours", w: 1.3, d: 0.9, layer: "wall-decor" },
    { id: "promo-board", label: "STORE SPECIALS", category: "wall", x: 9.84, y: 1.72, z: 3.05, prefab: "sign/promo-board", rotY: -1.571, w: 0.2, d: 1, layer: "wall-decor" },
    { id: "challenge-board", label: "CHALLENGE BOARD", category: "wall", x: -6.8, y: 1.62, z: 6.15, prefab: "sign/challenge-board", rotY: 3.142, w: 0.2, d: 0.72, layer: "wall-decor", interaction: {"type":"challenge","label":"Challenge Board"} },
    { id: "storefront-sign", label: "FRIDAY NIGHT VIDEO", category: "exterior", x: 0, y: 4.5, z: 7.5, prefab: "sign/storefront-marquee", w: 8, d: 0.2, layer: "exterior", meta: {"subtitle":"YOUR NEIGHBORHOOD VIDEO STORE"} },
    { id: "tv-left", label: "CRT TV (left)", category: "wall", x: -9.05, y: 2.2, z: 0, prefab: "prop/crt-tv", w: 0.3, d: 1.2, layer: "wall-decor", interaction: {"type":"tv","label":"Friday Night Pick"}, meta: {"yaw":1.3907963267948966,"tilt":0.12,"scale":0.84} },
    { id: "tv-right", label: "CRT TV (right)", category: "wall", x: 9.28, y: 2.26, z: 0, prefab: "prop/crt-tv", w: 0.3, d: 1, layer: "wall-decor", interaction: {"type":"tv","label":"Friday Night Pick"}, meta: {"yaw":-1.3907963267948966,"tilt":0.12,"scale":0.7} },
    { id: "bulletin-board", label: "Bulletin Board", category: "wall", x: -9.92, y: 1.6, z: 4.8, prefab: "prop/bulletin-board", rotY: 1.571, w: 0.2, d: 1.2, layer: "wall-decor" },
    { id: "clock-counter", label: "Wall Clock", category: "wall", x: 9.9, y: 2.8, z: 6.2, prefab: "prop/wall-clock", rotY: -1.571, w: 0.5, d: 0.5, layer: "wall-decor" },
    { id: "employees-door", label: "EMPLOYEES ONLY", category: "door", x: -9.93, y: 0, z: -5.19, rotY: 1.571, w: 0.2, d: 0.9, layer: "door" },
    { id: "pizza-building", label: "PIZZA PALACE", category: "exterior", x: -13, y: 0, z: 7, w: 6, d: 0.3, layer: "exterior" },
    { id: "pizza-door", label: "Pizza Door", category: "exterior", x: -12.5, y: 0, z: 7.16, w: 1, d: 0.2, layer: "exterior" },
    { id: "pizza-window", label: "Pizza Window", category: "exterior", x: -13.8, y: 0, z: 7.17, w: 2, d: 0.2, layer: "exterior" },
    { id: "laundro-building", label: "LAUNDROMAT", category: "exterior", x: 13, y: 0, z: 7, w: 6, d: 0.3, layer: "exterior" },
    { id: "laundro-door", label: "Laundro Door", category: "exterior", x: 13.5, y: 0, z: 7.16, w: 1, d: 0.2, layer: "exterior" },
    { id: "laundro-window", label: "Laundro Window", category: "exterior", x: 12, y: 0, z: 7.17, w: 2.2, d: 0.2, layer: "exterior" },
    { id: "laundro-open", label: "Laundro OPEN", category: "exterior", x: 11.2, y: 0, z: 7.25, prefab: "sign/open", w: 0.7, d: 0.35, layer: "wall-decor" },
    { id: "sidewalk", label: "Sidewalk", category: "exterior", x: 0, y: 0, z: 7.8, w: 22, d: 1.5, layer: "exterior" },
    { id: "car-sedan", label: "Sedan", category: "exterior", x: 5.45, y: 0, z: 12.22, prefab: "exterior/car", rotY: 1.571, w: 4.45, d: 1.82, layer: "exterior", collider: {"type":"box","enabled":true,"width":2.06,"depth":4.72} },
    { id: "car-van", label: "Van", category: "exterior", x: -4.76, y: 0, z: 12.55, prefab: "exterior/car", rotY: 1.571, w: 4.75, d: 1.9, layer: "exterior", collider: {"type":"box","enabled":true,"width":2.14,"depth":5.02} },
    { id: "car-suv", label: "SUV", category: "exterior", x: 2.42, y: 0, z: 12.37, prefab: "exterior/car", rotY: 1.571, w: 4.6, d: 1.92, layer: "exterior", collider: {"type":"box","enabled":true,"width":2.16,"depth":4.88} },
    { id: "car-hatchback", label: "Hatchback", category: "exterior", x: -8.24, y: 0, z: 12.62, prefab: "exterior/car", rotY: 1.571, w: 4.02, d: 1.76, layer: "exterior", collider: {"type":"box","enabled":true,"width":2,"depth":4.28} },
    { id: "car-taxi", label: "Taxi", category: "exterior", x: 8.19, y: 0, z: 12.39, prefab: "exterior/car", rotY: 1.571, w: 4.45, d: 1.82, layer: "exterior", collider: {"type":"box","enabled":true,"width":2.06,"depth":4.72} },
    { id: "car-sedan2", label: "Sedan 2", category: "exterior", x: -12.75, y: 0, z: 11.56, prefab: "exterior/car", rotY: 1.571, w: 4.35, d: 1.8, layer: "exterior", collider: {"type":"box","enabled":true,"width":2.04,"depth":4.62} },
    { id: "car-police", label: "Police Car", category: "exterior", x: 12.86, y: 0, z: 13.92, prefab: "exterior/car", w: 4.55, d: 1.84, layer: "exterior", collider: {"type":"box","enabled":true,"width":4.82,"depth":2.08} },
    { id: "car-delivery", label: "Delivery Van", category: "exterior", x: -2.36, y: 0, z: 12.26, prefab: "exterior/car", rotY: 1.571, w: 4.95, d: 1.96, layer: "exterior", collider: {"type":"box","enabled":true,"width":2.2,"depth":5.24} },
    { id: "lamp-1", label: "Lamp Post", category: "exterior", x: -5.94, y: 0, z: 18.2, prefab: "exterior/lamp-post", w: 0.3, d: 0.3, layer: "exterior", collider: {"type":"box","enabled":true,"width":0.6,"depth":0.6} },
    { id: "lamp-2", label: "Lamp Post", category: "exterior", x: 1.18, y: 0, z: 18.41, prefab: "exterior/lamp-post", w: 0.3, d: 0.3, layer: "exterior", collider: {"type":"box","enabled":true,"width":0.6,"depth":0.6} },
    { id: "lamp-3", label: "Lamp Post", category: "exterior", x: 8.18, y: 0, z: 18.12, prefab: "exterior/lamp-post", w: 0.3, d: 0.3, layer: "exterior", collider: {"type":"box","enabled":true,"width":0.6,"depth":0.6} },
  ],
};

// ── Helpers ──────────────────────────────────────────────

const _objectMap = new Map<string, LayoutObject>();
for (const obj of STORE_LAYOUT.objects) {
  _objectMap.set(obj.id, obj);
}

export function getObjectById(id: string): LayoutObject | undefined {
  return _objectMap.get(id);
}

export function getObjectsByCategory(category: ObjCategory): LayoutObject[] {
  return STORE_LAYOUT.objects.filter(o => o.category === category);
}

function mergeColliderDefaults(
  obj: LayoutObject,
  prefabCollider: LayoutCollider | undefined
): LayoutCollider | undefined {
  if (obj.collider?.enabled === false) return undefined;
  if (!obj.collider && !prefabCollider) return undefined;

  return {
    type: "box",
    enabled: true,
    width: obj.collider?.width ?? prefabCollider?.width ?? obj.w,
    depth: obj.collider?.depth ?? prefabCollider?.depth ?? obj.d,
    offsetX: obj.collider?.offsetX ?? prefabCollider?.offsetX ?? 0,
    offsetZ: obj.collider?.offsetZ ?? prefabCollider?.offsetZ ?? 0,
  };
}

function resolveInteractionDefaults(
  obj: LayoutObject,
  prefab: ReturnType<typeof resolvePrefabDefinition>
): LayoutInteraction | undefined {
  if (obj.interaction) return obj.interaction;

  if (prefab?.id === "shelf/gondola" || prefab?.id === "shelf/wall-run") {
    const genre =
      typeof obj.meta?.genre === "string" ? obj.meta.genre : obj.label;
    return {
      type: "shelf",
      label: "Browse " + genre,
      data: genre.toLowerCase().replace(/[- ]/g, ""),
    };
  }

  if (prefab?.id === "shelf/new-releases-wall") {
    return {
      type: "shelf",
      label: "Browse NEW RELEASES",
      data: "new",
    };
  }

  return prefab?.defaultInteraction;
}

export function resolveLayoutObject(obj: LayoutObject): ResolvedLayoutObject {
  const prefab = resolvePrefabDefinition(obj);

  return {
    ...obj,
    prefabId: obj.prefab || prefab?.id,
    hidden: obj.hidden ?? false,
    locked: obj.locked ?? false,
    layer: obj.layer ?? prefab?.defaultLayer ?? obj.category,
    interaction: resolveInteractionDefaults(obj, prefab),
    collider: mergeColliderDefaults(obj, prefab?.defaultCollider),
  };
}

export function getResolvedLayoutObjects(): ResolvedLayoutObject[] {
  return STORE_LAYOUT.objects.map(resolveLayoutObject);
}

export function getVisibleLayoutObjects(): ResolvedLayoutObject[] {
  return getResolvedLayoutObjects().filter((obj) => !obj.hidden);
}

export function getLayoutColliders(): WorldCollider[] {
  return getVisibleLayoutObjects()
    .filter((obj) => obj.collider?.enabled !== false && obj.collider?.width && obj.collider?.depth)
    .map((obj) => ({
      id: obj.id,
      x: obj.x + (obj.collider?.offsetX ?? 0),
      z: obj.z + (obj.collider?.offsetZ ?? 0),
      hw: (obj.collider?.width ?? 0) / 2,
      hd: (obj.collider?.depth ?? 0) / 2,
    }));
}

export function getLayoutInteractionObjects(): ResolvedLayoutObject[] {
  return getVisibleLayoutObjects().filter((obj) => Boolean(obj.interaction));
}

/**
 * Returns shelf rows in the same format Store.tsx SHELF_ROWS used to use.
 * Only includes gondola shelves (not wall shelves).
 */
export function getShelfRows(): { x: number; z: number; genre: string; color: string; backGenre: string; backColor: string; rotY: number }[] {
  return STORE_LAYOUT.objects
    .filter(o => o.id.startsWith("shelf-row"))
    .map(o => ({
      x: o.x,
      z: o.z,
      genre: (o.meta?.genre as string) || "",
      color: (o.meta?.color as string) || "#8B5E3C",
      backGenre: (o.meta?.backGenre as string) || "",
      backColor: (o.meta?.backColor as string) || "#444",
      rotY: o.rotY || 0,
    }));
}
