import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import type { StoreLayout } from "@/lib/store-layout";

const LAYOUT_FILE = path.join(process.cwd(), "src/lib/store-layout.ts");

// ── GET: return current layout as JSON ──
export async function GET() {
  try {
    // Dynamic import to always get the latest version
    // We read the file and parse the data from it instead of using the cached module
    const fileContent = fs.readFileSync(LAYOUT_FILE, "utf-8");

    // Extract the objects array from the TypeScript source
    const match = fileContent.match(/objects:\s*\[([\s\S]*?)\],\s*\};/);
    if (!match) {
      // Fallback: import the module directly
      const mod = await import("@/lib/store-layout");
      return NextResponse.json(mod.STORE_LAYOUT);
    }

    // Use the module import for reliable parsing
    const mod = await import("@/lib/store-layout");
    return NextResponse.json(mod.STORE_LAYOUT);
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}

// ── POST: update layout by rewriting the source file ──
export async function POST(req: Request) {
  try {
    const layout: StoreLayout = await req.json();

    if (!layout.version || !Array.isArray(layout.objects)) {
      return NextResponse.json({ error: "Invalid layout: needs version and objects array" }, { status: 400 });
    }

    // Generate the TypeScript source code
    const source = generateLayoutSource(layout);

    fs.writeFileSync(LAYOUT_FILE, source, "utf-8");

    return NextResponse.json({ success: true, objectCount: layout.objects.length });
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}

function generateLayoutSource(layout: StoreLayout): string {
  const lines: string[] = [];

  lines.push(`/**
 * store-layout.ts — Single source of truth for all positioned objects in the 3D store.
 *
 * Categories:
 *   shelf    — gondola shelves and wall shelves
 *   counter  — checkout counter
 *   npc      — Vinny, Charlie, Kid, Tarantino, customers
 *   prop     — cooler, trophy shelf, bargain bin, detail items, etc.
 *   wall     — posters, signs, TV, bulletin board
 *   door     — entrance, employees only
 *   exterior — Pizza Palace, Laundromat, cars, lamps, etc.
 *
 * AUTO-GENERATED by /api/layout POST — do not edit manually.
 */

import { resolvePrefabDefinition } from "./store-prefabs";

// ── Types ────────────────────────────────────────────────

export type ObjCategory = "shelf" | "counter" | "npc" | "prop" | "wall" | "door" | "exterior";

export interface LayoutInteraction {
  type: string;
  label: string;
  data?: string;
}

export interface LayoutCollider {
  type: "box";
  enabled?: boolean;
  width?: number;
  depth?: number;
  offsetX?: number;
  offsetZ?: number;
}

export interface LayoutObject {
  id: string;
  label: string;
  category: ObjCategory;
  x: number;
  y: number;
  z: number;
  prefab?: string;
  rotY?: number;
  w?: number;
  d?: number;
  hidden?: boolean;
  locked?: boolean;
  layer?: string;
  interaction?: LayoutInteraction;
  collider?: LayoutCollider;
  meta?: Record<string, unknown>;
}

export interface StoreLayout {
  version: number;
  objects: LayoutObject[];
}

export interface ResolvedLayoutObject extends LayoutObject {
  prefabId?: string;
  hidden: boolean;
  locked: boolean;
  layer: string;
  interaction?: LayoutInteraction;
  collider?: LayoutCollider;
}

export interface WorldCollider {
  id: string;
  x: number;
  z: number;
  hw: number;
  hd: number;
}

// ── Layout Data ──────────────────────────────────────────

export const STORE_LAYOUT: StoreLayout = {
  version: ${layout.version},
  objects: [`);

  for (const obj of layout.objects) {
    const parts: string[] = [];
    parts.push(`id: ${JSON.stringify(obj.id)}`);
    parts.push(`label: ${JSON.stringify(obj.label)}`);
    parts.push(`category: ${JSON.stringify(obj.category)}`);
    parts.push(`x: ${obj.x}`);
    parts.push(`y: ${obj.y}`);
    parts.push(`z: ${obj.z}`);
    if (obj.prefab) parts.push(`prefab: ${JSON.stringify(obj.prefab)}`);
    if (obj.rotY !== undefined && obj.rotY !== 0) parts.push(`rotY: ${obj.rotY}`);
    if (obj.w !== undefined) parts.push(`w: ${obj.w}`);
    if (obj.d !== undefined) parts.push(`d: ${obj.d}`);
    if (obj.hidden) parts.push(`hidden: true`);
    if (obj.locked) parts.push(`locked: true`);
    if (obj.layer) parts.push(`layer: ${JSON.stringify(obj.layer)}`);
    if (obj.interaction) parts.push(`interaction: ${JSON.stringify(obj.interaction)}`);
    if (obj.collider) parts.push(`collider: ${JSON.stringify(obj.collider)}`);
    if (obj.meta && Object.keys(obj.meta).length > 0) {
      parts.push(`meta: ${JSON.stringify(obj.meta)}`);
    }
    lines.push(`    { ${parts.join(", ")} },`);
  }

  lines.push(`  ],
};

// ── Helpers ──────────────────────────────────────────────

const _objectMap = new Map<string, LayoutObject>();
for (const obj of STORE_LAYOUT.objects) {
  _objectMap.set(obj.id, obj);
}

export function getObjectById(id: string): LayoutObject | undefined {
  return _objectMap.get(id);
}

export function getObjectsByCategory(category: ObjCategory): LayoutObject[] {
  return STORE_LAYOUT.objects.filter(o => o.category === category);
}

function mergeColliderDefaults(
  obj: LayoutObject,
  prefabCollider: LayoutCollider | undefined
): LayoutCollider | undefined {
  if (obj.collider?.enabled === false) return undefined;
  if (!obj.collider && !prefabCollider) return undefined;

  return {
    type: "box",
    enabled: true,
    width: obj.collider?.width ?? prefabCollider?.width ?? obj.w,
    depth: obj.collider?.depth ?? prefabCollider?.depth ?? obj.d,
    offsetX: obj.collider?.offsetX ?? prefabCollider?.offsetX ?? 0,
    offsetZ: obj.collider?.offsetZ ?? prefabCollider?.offsetZ ?? 0,
  };
}

export function resolveLayoutObject(obj: LayoutObject): ResolvedLayoutObject {
  const prefab = resolvePrefabDefinition(obj);

  return {
    ...obj,
    prefabId: obj.prefab || prefab?.id,
    hidden: obj.hidden ?? false,
    locked: obj.locked ?? false,
    layer: obj.layer ?? prefab?.defaultLayer ?? obj.category,
    interaction: obj.interaction ?? prefab?.defaultInteraction,
    collider: mergeColliderDefaults(obj, prefab?.defaultCollider),
  };
}

export function getResolvedLayoutObjects(): ResolvedLayoutObject[] {
  return STORE_LAYOUT.objects.map(resolveLayoutObject);
}

export function getVisibleLayoutObjects(): ResolvedLayoutObject[] {
  return getResolvedLayoutObjects().filter((obj) => !obj.hidden);
}

export function getLayoutColliders(): WorldCollider[] {
  return getVisibleLayoutObjects()
    .filter((obj) => obj.collider?.enabled !== false && obj.collider?.width && obj.collider?.depth)
    .map((obj) => ({
      id: obj.id,
      x: obj.x + (obj.collider?.offsetX ?? 0),
      z: obj.z + (obj.collider?.offsetZ ?? 0),
      hw: (obj.collider?.width ?? 0) / 2,
      hd: (obj.collider?.depth ?? 0) / 2,
    }));
}

export function getLayoutInteractionObjects(): ResolvedLayoutObject[] {
  return getVisibleLayoutObjects().filter((obj) => Boolean(obj.interaction));
}

/**
 * Returns shelf rows in the same format Store.tsx SHELF_ROWS used to use.
 * Only includes gondola shelves (not wall shelves).
 */
export function getShelfRows(): { x: number; z: number; genre: string; color: string; backGenre: string; backColor: string; rotY: number }[] {
  return STORE_LAYOUT.objects
    .filter(o => o.id.startsWith("shelf-row"))
    .map(o => ({
      x: o.x,
      z: o.z,
      genre: (o.meta?.genre as string) || "",
      color: (o.meta?.color as string) || "#8B5E3C",
      backGenre: (o.meta?.backGenre as string) || "",
      backColor: (o.meta?.backColor as string) || "#444",
      rotY: o.rotY || 0,
    }));
}
`);

  return lines.join("\n");
}
